r=int(input("enter the radius of circle"))
a=3.14*r**2
print("area of the circle=",a)
l=int(input("enter the length"))
b=int(input("enter the width"))
ar=l*b
print("area of rectangle= ",ar)
h=int(input("enter the height"))
base=int(input("enter the value"))
area=0.5*base*h
print("area of triangle=",area)